import json

from pytest_cookies.plugin import Cookies

from .helper import generate_cookiecutter_context


def test_bake_cookiecutter_json(cookies: Cookies):
    context = generate_cookiecutter_context()
    result = cookies.bake(extra_context=context)
    assert not result.exception

    with result.project_path.joinpath('cookiecutter.json').open('r', encoding='utf-8') as fp:
        assert json.load(fp)['project_description'] == f'New project generated by {context["template_slug"]}'
